# Enterpolasyon

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
s = pd.Series([0,1,np.nan,3])
print(s)

0    0.0
1    1.0
2    NaN
3    3.0
dtype: float64


In [ ]:
s.interpolate()

0    0.0
1    1.0
2    2.0
3    3.0
dtype: float64

In [ ]:
from sklearn.impute import KNNImputer

In [ ]:
X = [[1,2,np.nan],[3,4,3],[np.nan,6,5],[8,8,7]]

In [ ]:
pd.DataFrame(X)

0  1    2
0  1.0  2  NaN
1  3.0  4  3.0
2  NaN  6  5.0
3  8.0  8  7.0

In [ ]:
imputer = KNNImputer(n_neighbors = 2, weights="distance")
X= imputer.fit_transform(X)

In [ ]:
pd.DataFrame(X)

0    1    2
0  1.0  2.0  4.0
1  3.0  4.0  3.0
2  5.5  6.0  5.0
3  8.0  8.0  7.0

In [ ]:
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky','John','Elise'],'Surname':['Smith','Jones','Williams','Taylor','Davies','Brown'],
        'Age':[28,np.nan,29,24,23,22],'City':['Boston','Kansas','New York','Colorado','Washington',np.nan]}
df=pd.DataFrame(data)
print(df)

    Name   Surname  Age        City
0    Tom     Smith   28      Boston
1   Jack     Jones  nan      Kansas
2  Steve  Williams   29    New York
3  Ricky    Taylor   24    Colorado
4   John    Davies   23  Washington
5  Elise     Brown   22         NaN


In [ ]:
df.Name

0      Tom
1     Jack
2    Steve
3    Ricky
4     John
5    Elise
Name: Name, dtype: object

In [ ]:
df.City=df.City.replace(np.nan,"Other")
df.Age=df.Age.replace(np.nan,df.Age.mean())
#round(df.Age)
#df.Age=df.Age.fillna(df.Age.mean()).astype(int)
#pd.options.display.float_format =   '{:,.0f}'.format
df.Age


# Scaling

In [ ]:
from sklearn.preprocessing  import StandardScaler

In [ ]:
df_ss = df.copy()
df.Age

0   28
1   25
2   29
3   24
4   23
5   22
Name: Age, dtype: float64

In [ ]:
df_ss["Age_Scaled"] = StandardScaler().fit_transform(df_ss[['Age']])

In [ ]:
print(df_ss.Age.mean())
print(df_ss.Age.std())

25.2
2.7856776554368237


In [ ]:
print(df_ss.Age_Scaled.mean())
print(df_ss.Age_Scaled.std())

In [ ]:
df_ss.Age_Scaled

0    1
1    0
2    1
3   -0
4   -1
5   -1
Name: Age_Scaled, dtype: float64

# MinMaxScaler

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
df_mm= df.copy()

In [ ]:

df_mm['Age_Scaled'] = MinMaxScaler().fit_transform(df_mm[['Age']])
df_mm

Name   Surname  Age        City  Age_Scaled
0    Tom     Smith   28      Boston           1
1   Jack     Jones   25      Kansas           0
2  Steve  Williams   29    New York           1
3  Ricky    Taylor   24    Colorado           0
4   John    Davies   23  Washington           0
5  Elise     Brown   22       Other           0

## **Label Encoding**

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder() 

In [ ]:
df_le = df.copy()

In [ ]:
le.fit(df_le["City"])
list(le.classes_)

['Boston', 'Colorado', 'Kansas', 'New York', 'Other', 'Washington']

In [ ]:
df_le.City = le.transform(df_le["City"])
df_le

Name   Surname  Age  City
0    Tom     Smith   28     0
1   Jack     Jones   25     2
2  Steve  Williams   29     3
3  Ricky    Taylor   24     1
4   John    Davies   23     5
5  Elise     Brown   22     4

In [ ]:
le.inverse_transform([2,1,0,1])

array(['Kansas', 'Colorado', 'Boston', 'Colorado'], dtype=object)

# **ONE HOT ENCODING**

In [ ]:
pd.get_dummies(df["City"])

Boston  Colorado  Kansas  New York  Other  Washington
0       1         0       0         0      0           0
1       0         0       1         0      0           0
2       0         0       0         1      0           0
3       0         1       0         0      0           0
4       0         0       0         0      0           1
5       0         0       0         0      1           0

# KUANTİZASYON BINDING

In [ ]:
X = np.array([[-3,5.,15],
              [0.,6.,14],
              [6.,3.,11]])
X

array([[-3.,  5., 15.],
       [ 0.,  6., 14.],
       [ 6.,  3., 11.]])

In [ ]:
from sklearn import preprocessing

In [ ]:
preprocessing.KBinsDiscretizer(n_bins=[3,2,2], encode="ordinal").fit_transform(X)

array([[0., 1., 1.],
       [1., 1., 1.],
       [2., 0., 0.]])

In [ ]:
binerizer = preprocessing.Binarizer(threshold=5.1)

In [ ]:
binerizer.transform(X)

array([[0., 0., 1.],
       [0., 1., 1.],
       [1., 0., 1.]])